# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "윤진"
description:        "이윤진의 개발블로그"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://yj-java-kor.github.io/blog"
author:             "gfjaru"
twitter:
  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "https://yj-java-kor.github.io/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "윤진이의 개발일지"
    remote:         false
    localpath:      "about"
 

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
